/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.Login;
import com.data.UserDao;
import com.data.UserDaoImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author Rosi
 */
public class ChangePassword extends javax.swing.JFrame {

	/**
	 * Creates new form SistemCetakGUI
	 */
	public ChangePassword() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        formNewPass = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        formNIM = new javax.swing.JTextField();
        formOldPass = new javax.swing.JPasswordField();
        buttonSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITB Printing Service");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("ITB Printing Service"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("Ganti password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 230, 90, 15);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 30, 37, 15);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Ganti password");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(600, 30, 81, 15);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("Rosiana Rozi (13512666)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 30, 123, 15);

        formNewPass.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        formNewPass.setText("New password");
        formNewPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        formNewPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formNewPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formNewPassFocusLost(evt);
            }
        });
        formNewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formNewPassMouseClicked(evt);
            }
        });
        getContentPane().add(formNewPass);
        formNewPass.setBounds(336, 320, 151, 22);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("ITB Printing Service");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 99, 194)));
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(-10, 0, 340, 50);

        formNIM.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        formNIM.setText("NIM");
        formNIM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        formNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formNIMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formNIMFocusLost(evt);
            }
        });
        formNIM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formNIMMouseClicked(evt);
            }
        });
        formNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formNIMActionPerformed(evt);
            }
        });
        getContentPane().add(formNIM);
        formNIM.setBounds(336, 264, 151, 22);

        formOldPass.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        formOldPass.setText("Old password");
        formOldPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        formOldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formOldPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formOldPassFocusLost(evt);
            }
        });
        formOldPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formOldPassMouseClicked(evt);
            }
        });
        formOldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formOldPassActionPerformed(evt);
            }
        });
        getContentPane().add(formOldPass);
        formOldPass.setBounds(336, 292, 151, 22);

        buttonSubmit.setBackground(new java.awt.Color(138, 138, 255));
        buttonSubmit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        buttonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubmit.setText("OK");
        buttonSubmit.setAlignmentX(0.5F);
        buttonSubmit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSubmit.setPreferredSize(new java.awt.Dimension(50, 25));
        buttonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSubmitMouseClicked(evt);
            }
        });
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSubmit);
        buttonSubmit.setBounds(390, 360, 50, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bg2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNIMActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_formNIMActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSubmitMouseClicked
		// TODO add your handling code here:

		UserDao data = new UserDaoImpl();
		com.data.User userData = data.Validate(formNIM.getText(), formOldPass.getText());
		userData.print();
		if (userData != null) {
			this.hide();
			userData.setPassword(formNewPass.getText());
			userData.print();
			data.UpdateUser(userData.getUsername(), userData);
			User user = new User();
			user.show();

		} else {
			JOptionPane.showMessageDialog(this, "Wrong username or password!");
		}
    }//GEN-LAST:event_buttonSubmitMouseClicked

    private void formNIMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formNIMMouseClicked
		// TODO add your handling code here:
		formNIM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
		formNIM.setText("");
    }//GEN-LAST:event_formNIMMouseClicked

    private void formOldPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formOldPassMouseClicked
		// TODO add your handling code here:
		formOldPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
    }//GEN-LAST:event_formOldPassMouseClicked

    private void formNIMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formNIMFocusGained
		// TODO add your handling code here:
		formNIM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
		formNIM.setText("");
    }//GEN-LAST:event_formNIMFocusGained

    private void formOldPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formOldPassFocusGained
		// TODO add your handling code here:
		formOldPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
		formOldPass.setText("");
    }//GEN-LAST:event_formOldPassFocusGained

    private void formNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formNIMFocusLost
		// TODO add your handling code here:
		formNIM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
		if (formNIM.getText().equals("")) {
			formNIM.setText("Username");
		}
    }//GEN-LAST:event_formNIMFocusLost

    private void formOldPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formOldPassFocusLost
		// TODO add your handling code here:
		formOldPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
		if (formOldPass.getText().equals("")) {
			formOldPass.setText("Password");
		}
    }//GEN-LAST:event_formOldPassFocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formNewPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formNewPassFocusGained
		// TODO add your handling code here:
		formNewPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
		formNewPass.setText("");
    }//GEN-LAST:event_formNewPassFocusGained

    private void formNewPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formNewPassFocusLost
		// TODO add your handling code here:
		formNewPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
		if (formNewPass.getText().equals("")) {
			formNewPass.setText("Password");
		}
    }//GEN-LAST:event_formNewPassFocusLost

    private void formNewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formNewPassMouseClicked
		// TODO add your handling code here:
    }//GEN-LAST:event_formNewPassMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
		// TODO add your handling code here:
		this.hide();
		Login login = new Login();
		login.show();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
		// TODO add your handling code here:
		this.hide();
		ChangePassword cpass = new ChangePassword();
		cpass.show();
    }//GEN-LAST:event_jButton6MouseClicked

    private void formOldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formOldPassActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_formOldPassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Main.client.logout();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JTextField formNIM;
    private javax.swing.JPasswordField formNewPass;
    private javax.swing.JPasswordField formOldPass;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
