/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import javax.swing.SwingUtilities;
import main.CalonTerpilih;
/**
 *
 * @author akhfa
 */
public class FormAdmin extends javax.swing.JFrame{

    /**
     * Creates new form FormAdmin
     */
    private CalonTerpilih DaftarPilihan;
    private Object AWTUtilities;
    
    public FormAdmin() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TombolDapil = new javax.swing.JButton();
        TombolDPR = new javax.swing.JButton();
        TombolDPD = new javax.swing.JButton();
        TombolDPRDProv = new javax.swing.JButton();
        TombolDPRDKotKab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TombolDapil.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        TombolDapil.setText("Daerah Pemilihan");
        TombolDapil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDapilActionPerformed(evt);
            }
        });

        TombolDPR.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        TombolDPR.setText("DPR");
        TombolDPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDPRActionPerformed(evt);
            }
        });

        TombolDPD.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        TombolDPD.setText("DPD");
        TombolDPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDPDActionPerformed(evt);
            }
        });

        TombolDPRDProv.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        TombolDPRDProv.setText("DPRD Provinsi");
        TombolDPRDProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDPRDProvActionPerformed(evt);
            }
        });

        TombolDPRDKotKab.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        TombolDPRDKotKab.setText("DPRD Kota/Kabupaten");
        TombolDPRDKotKab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolDPRDKotKabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TombolDPRDKotKab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TombolDPRDProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TombolDapil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TombolDPR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TombolDPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(TombolDapil)
                .addGap(18, 18, 18)
                .addComponent(TombolDPR)
                .addGap(18, 18, 18)
                .addComponent(TombolDPD)
                .addGap(18, 18, 18)
                .addComponent(TombolDPRDProv)
                .addGap(18, 18, 18)
                .addComponent(TombolDPRDKotKab)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolDapilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDapilActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FormDapil FD = new FormDapil();
        FD.setVisible(true);
        //this.setVisible(true);
        
    }//GEN-LAST:event_TombolDapilActionPerformed

    private void TombolDPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDPRActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FormCaleg FC = new FormCaleg("DPR");
        FC.setVisible(true);
    }//GEN-LAST:event_TombolDPRActionPerformed

    private void TombolDPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDPDActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FormCaleg FC = new FormCaleg("DPD");
        FC.setVisible(true);
    }//GEN-LAST:event_TombolDPDActionPerformed

    private void TombolDPRDProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDPRDProvActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FormCaleg FC = new FormCaleg("DPRD Provinsi");
        FC.setVisible(true);
    }//GEN-LAST:event_TombolDPRDProvActionPerformed

    private void TombolDPRDKotKabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolDPRDKotKabActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FormCaleg FC = new FormCaleg("DPRD Kota/Kabupaten");
        FC.setVisible(true);
    }//GEN-LAST:event_TombolDPRDKotKabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TombolDPD;
    private javax.swing.JButton TombolDPR;
    private javax.swing.JButton TombolDPRDKotKab;
    private javax.swing.JButton TombolDPRDProv;
    private javax.swing.JButton TombolDapil;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
