/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Tools.PasswordErrorException;
import javax.swing.JOptionPane;

/**
 *
 * @author akhfa
 */
public class FormLoginPemilih extends javax.swing.JFrame{
    private FormPemilih formPemilih;
    
    /**
     * Creates new form FormLoginPemilih
     */
    public FormLoginPemilih() {
        initComponents();
        jPasswordFieldPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        TombolLogin = new javax.swing.JButton();
        textFieldNIK = new java.awt.TextField();
        jLabelNIK = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jLabelLogin = new javax.swing.JLabel();
        jLabelPemilih = new javax.swing.JLabel();
        jLabelCenterBackground = new javax.swing.JLabel();
        jLabelBackDown = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TombolLogin.setBackground(java.awt.SystemColor.inactiveCaptionText);
        TombolLogin.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        TombolLogin.setForeground(new java.awt.Color(255, 153, 102));
        TombolLogin.setText("Log In");
        TombolLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TombolLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 80, -1));

        textFieldNIK.setBackground(new java.awt.Color(255, 255, 204));
        textFieldNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNIKActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 200, -1));
        textFieldNIK.getAccessibleContext().setAccessibleName("NIKinput");

        jLabelNIK.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabelNIK.setForeground(new java.awt.Color(255, 255, 204));
        jLabelNIK.setText("NIK");
        getContentPane().add(jLabelNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, 20));

        jLabelPassword.setFont(new java.awt.Font("Belwe Bd BT", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 204));
        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, 20));
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 702, -1, -1));

        jLabelLogin.setFont(new java.awt.Font("Belwe Bd BT", 0, 22)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(255, 255, 204));
        jLabelLogin.setText("Log In");
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabelPemilih.setFont(new java.awt.Font("Belwe Bd BT", 1, 36)); // NOI18N
        jLabelPemilih.setForeground(new java.awt.Color(255, 255, 204));
        jLabelPemilih.setText("Pemilih");
        getContentPane().add(jLabelPemilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabelCenterBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/shutterstock_47142253.jpg"))); // NOI18N
        getContentPane().add(jLabelCenterBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 140));

        jLabelBackDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/shutterstock_47142253.jpg"))); // NOI18N
        getContentPane().add(jLabelBackDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 590, 110));

        jPasswordFieldPassword.setBackground(new java.awt.Color(255, 255, 204));
        jPasswordFieldPassword.setText("jPasswordField1");
        getContentPane().add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 200, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/shutterstock_47142253.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 590, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNIKActionPerformed

    private void TombolLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolLoginActionPerformed
        formPemilih = new FormPemilih(textFieldNIK.getText(), jPasswordFieldPassword.getText());
        try{
            if(formPemilih.GetPemilih().ValidateInput()){
                this.dispose();
                formPemilih.setVisible(true);

            }
        }catch(PasswordErrorException er){
            JOptionPane.showMessageDialog(null, er.getMessage());
        }
    }//GEN-LAST:event_TombolLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLoginPemilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLoginPemilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLoginPemilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLoginPemilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLoginPemilih().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TombolLogin;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabelBackDown;
    private javax.swing.JLabel jLabelCenterBackground;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNIK;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPemilih;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.TextField textFieldNIK;
    // End of variables declaration//GEN-END:variables
}
