
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Winner extends javax.swing.JFrame {

    /**
     * Creates new form Winner
     */
    public Winner() {
        initComponents();
        setSize(1024,725);
        Background = new JLabel();
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/play.png")));
        getContentPane().add(Background);
        Background.setSize(getSize());
        int i = 2;
        if(i==1){
            Win.setText("Nature Win!");
            Pict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/nature.png")));
        }
        else{
            Win.setText("Human Win!");
            Pict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/human.png")));
        }
        setVisible(true);
    }
    
    public Winner(int i) {
        initComponents();
        setSize(1024,725);
        Background = new JLabel();
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/play.png")));
        getContentPane().add(Background);
        Background.setSize(getSize());
        if(i==1){
            Win.setText("Nature Win!");
            Pict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/nature.png")));
        }
        else{
            Win.setText("Human Win!");
            Pict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/human.png")));
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Win = new javax.swing.JLabel();
        OkButton = new javax.swing.JButton();
        Pict = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Win.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Win.setText("Selamat!");
        getContentPane().add(Win);
        Win.setBounds(350, 100, 430, 230);

        OkButton.setText("Back to Main Menu");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OkButton);
        OkButton.setBounds(380, 560, 210, 70);
        getContentPane().add(Pict);
        Pict.setBounds(400, 260, 210, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        dispose(); //Destroy the JFrame object
        setVisible(false);
        new MainMenu();
    }//GEN-LAST:event_OkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Winner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Winner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Winner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Winner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Winner().setVisible(true);
            }
        });
    }
    private JLabel Background;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkButton;
    private javax.swing.JLabel Pict;
    private javax.swing.JLabel Win;
    // End of variables declaration//GEN-END:variables
}
